name: C/C++ CI

on:
  push:
    branches:
      - master
      - MPI_Development
      - cmake_development
      - parUpscale

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        mpi:
          - mpich
          - openmpi
          - msmpi
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        exclude:
          - os: ubuntu-latest
            mpi: msmpi
          - os: macos-latest
            mpi: msmpi
          - os: windows-latest
            mpi: mpich
          - os: windows-latest
            mpi: openmpi
    
    steps:
    # Get dependencies
    - name: Get dependencies (${{ matrix.mpi }})
      if:   runner.os == 'Linux'
      run:  sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev cppcheck
      
    - name: Get dependencies (${{ matrix.mpi }})
      if:   runner.os == 'macOS'
      run:  sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev cppcheck
          
    # Checkout v2 : https://github.com/actions/checkout
    - uses: actions/checkout@v2
      
    # Check CMake Version 
    - name: Check CMake (${{ matrix.mpi }})
      run: cmake --version
      
    # Make the project
    - name: cmake
      run: cmake . && make
  
    # Run cmake tests
    - name: ctest
      run: make test
    
    - name: cppcheck
      if:   runner.os == 'Linux'
      run:  cppcheck --enable=all --force .
